<?xml version="1.0" encoding="UTF-8"?>
<testsuites>
  <testsuite name="Modelo_model_test" file="/home/ademir/www/xy-inc/application/tests/modules/modelo/models/Modelo_model_test.php" tests="7" assertions="23" failures="1" errors="0" time="2.222923">
    <testcase name="test_createModelo" class="Modelo_model_test" file="/home/ademir/www/xy-inc/application/tests/modules/modelo/models/Modelo_model_test.php" line="17" assertions="21" time="0.594125"/>
    <testcase name="test_createModeloFalhaDuplicarModelo" class="Modelo_model_test" file="/home/ademir/www/xy-inc/application/tests/modules/modelo/models/Modelo_model_test.php" line="64" assertions="0" time="0.415063">
      <failure type="PHPUnit_Framework_AssertionFailedError">Modelo_model_test::test_createModeloFalhaDuplicarModelo
No exception has been raised

/home/ademir/www/xy-inc/application/tests/modules/modelo/models/Modelo_model_test.php:91
</failure>
    </testcase>
    <testcase name="test_createModeloFalhaCriarModelo" class="Modelo_model_test" file="/home/ademir/www/xy-inc/application/tests/modules/modelo/models/Modelo_model_test.php" line="94" assertions="0" time="0.249050"/>
    <testcase name="test_createModeloFalhaSalvarRegistroModelo" class="Modelo_model_test" file="/home/ademir/www/xy-inc/application/tests/modules/modelo/models/Modelo_model_test.php" line="124" assertions="0" time="0.263727"/>
    <testcase name="test_createModeloFalhaSalvarRegistroModeloInputs" class="Modelo_model_test" file="/home/ademir/www/xy-inc/application/tests/modules/modelo/models/Modelo_model_test.php" line="135" assertions="0" time="0.259127"/>
    <testcase name="test_dropModelo" class="Modelo_model_test" file="/home/ademir/www/xy-inc/application/tests/modules/modelo/models/Modelo_model_test.php" line="158" assertions="1" time="0.211924"/>
    <testcase name="test_existeModelo" class="Modelo_model_test" file="/home/ademir/www/xy-inc/application/tests/modules/modelo/models/Modelo_model_test.php" line="163" assertions="1" time="0.229907"/>
  </testsuite>
</testsuites>
